version: '3.7'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
    stdin_open: true
    command: npm start